DROP TABLE IF EXISTS logs;

CREATE TABLE logs(
LogId INT UNSIGNED NOT NULL AUTO_INCREMENT,
SvrId INT UNSIGNED NOT NULL DEFAULT 0,
UsrId INT UNSIGNED NOT NULL DEFAULT 0,
UsrName VARCHAR(64) NOT NULL DEFAULT '0',
LogType INT UNSIGNED NOT NULL DEFAULT 0,
LogTime DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
LogKey VARCHAR(4096) NOT NULL DEFAULT '0',
LogMsg VARCHAR(4096) NOT NULL DEFAULT '0',
PRIMARY KEY (`LogId`),
KEY `SvrIdIndex`   (`SvrId`),
KEY `UsrIdIndex`   (`UsrId`),
KEY `UsrNameIndex` (`UsrName`),
KEY `LogTypeIndex` (`LogType`),
KEY `LogKeyIndex`  (`LogKey`))
ENGINE = MyISAM;
